# ESP32-S3-Touch-LCD-7
substitutions:
  name: "meterkast-display"
  friendly_name: "Meterkast"

# Wifi Setup
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Packages
packages:
  setup:
    url: https://github.com/jtenniswood/esphome-lvgl/
    files: [device/esp32-s3-touch-lcd-7.yaml,
            addon/time.yaml,
            addon/backlight.yaml,
            addon/network.yaml,
            assets/fonts.yaml,
            assets/icons.yaml,
            theme/button.yaml,
            meterkast/sensors.yaml,
            meterkast/lvgl.yaml]
    refresh: 1sec
