text_sensor:
  - platform: homeassistant
    id: airco_1_state
    entity_id: climate.airco_lokaal_1_airco
    attribute: state
  - platform: homeassistant
    id: airco_2_state
    entity_id: climate.airco_lokaal_2_airco
    attribute: state
  - platform: homeassistant
    id: airco_3_state
    entity_id: climate.airco_lokaal_3_airco
    attribute: state
  - platform: homeassistant
    id: airco_4_state
    entity_id: climate.airco_lokaal_4_airco
    attribute: state
  - platform: homeassistant
    id: airco_5_state
    entity_id: climate.airco_lokaal_5_airco
    attribute: state
  - platform: homeassistant
    id: airco_6_state
    entity_id: climate.airco_lokaal_6_airco
    attribute: state
  - platform: homeassistant
    id: airco_8_state
    entity_id: climate.airco_lokaal_8_airco
    attribute: state
  - platform: homeassistant
    id: airco_9_state
    entity_id: climate.airco_lokaal_9_airco
    attribute: state

binary_sensor:
  - platform: template
    id: airco_1_switch
    lambda: |-
      if (id(airco_1_state).has_state()) {
        std::string state = id(airco_1_state).state;
        return state != "off" && state != "idle";
      }
      return false;
    on_state:
      then:
        - lvgl.widget.update:
            id: lokaal1
            state:
              checked: !lambda return x;
  - platform: template
    id: airco_2_switch
    lambda: |-
      if (id(airco_2_state).has_state()) {
        std::string state = id(airco_2_state).state;
        return state != "off" && state != "idle";
      }
      return false;
    on_state:
      then:
        - lvgl.widget.update:
            id: lokaal2
            state:
              checked: !lambda return x;
  - platform: template
    id: airco_3_switch
    lambda: |-
      if (id(airco_3_state).has_state()) {
        std::string state = id(airco_3_state).state;
        return state != "off" && state != "idle";
      }
      return false;
    on_state:
      then:
        - lvgl.widget.update:
            id: lokaal3
            state:
              checked: !lambda return x;
  - platform: template
    id: airco_4_switch
    lambda: |-
      if (id(airco_4_state).has_state()) {
        std::string state = id(airco_4_state).state;
        return state != "off" && state != "idle";
      }
      return false;
    on_state:
      then:
        - lvgl.widget.update:
            id: lokaal4
            state:
              checked: !lambda return x;
  - platform: template
    id: airco_5_switch
    lambda: |-
      if (id(airco_5_state).has_state()) {
        std::string state = id(airco_5_state).state;
        return state != "off" && state != "idle";
      }
      return false;
    on_state:
      then:
        - lvgl.widget.update:
            id: lokaal5
            state:
              checked: !lambda return x;
  - platform: template
    id: airco_6_switch
    lambda: |-
      if (id(airco_6_state).has_state()) {
        std::string state = id(airco_6_state).state;
        return state != "off" && state != "idle";
      }
      return false;
    on_state:
      then:
        - lvgl.widget.update:
            id: lokaal6
            state:
              checked: !lambda return x;
  - platform: template
    id: airco_8_switch
    lambda: |-
      if (id(airco_8_state).has_state()) {
        std::string state = id(airco_8_state).state;
        return state != "off" && state != "idle";
      }
      return false;
    on_state:
      then:
        - lvgl.widget.update:
            id: lokaal8
            state:
              checked: !lambda return x;
