binary_sensor:
  - platform: homeassistant
    id: airco_1_status
    entity_id: climate.airco_lokaal_1_airco
    on_state:
      then:
        - lvgl.widget.update:
            id: lokaal1
            checked: !lambda 'return x == "off";'