homeassistant:
  - id: airco_status
    entity_id: climate.airco_lokaal_1_airco
    attribute: hvac_action
    on_value:
      then:
        - lvgl.widget.update:
            id: veldverlichting
            checked: !lambda 'return x == "off";'