text_sensor:
  - platform: homeassistant
    entity_id: climate.airco_lokaal_1_airco
    id: airco_1_state
    # Verwijder de 'attribute: state' regel - de state wordt automatisch gesynchroniseerd

binary_sensor:
  - platform: template
    id: airco_1_switch
    lambda: |-
      if (id(airco_1_state).has_state()) {
        std::string state = id(airco_1_state).state;
        return state != "off" && state != "idle";
      }
      return false;
    on_state:
      then:
        - lvgl.widget.update:
            id: lokaal1
            state:
              checked: !lambda return x;

interval:
  - interval: 10s
    then:
      - lambda: |-
          if (id(airco_1_state).has_state()) {
            ESP_LOGI("airco_log", "Airco 1 state: %s", id(airco_1_state).state.c_str());
          } else {
            ESP_LOGI("airco_log", "Airco 1 state: no state yet");
          }