text_sensor:
  - platform: homeassistant
    id: airco_1_state
    entity_id: climate.airco_lokaal_1_airco

binary_sensor:
  - platform: template
    id: airco_1_switch
    lambda: |-
      if (id(airco_1_state).has_state()) {
        std::string state = id(airco_1_state).state;
        return state != "off" && state != "idle";
      }
      return false;
    on_state:
      then:
        - lvgl.widget.update:
            id: lokaal1
            state:
              checked: !lambda |-
                return !x;

interval:
  - interval: 10s
    then:
      - lambda: |-
          ESP_LOGI("airco", "Airco status update:");
          ESP_LOGI("airco", "  Airco 1: %s", id(airco_1_state).state.c_str());