text_sensor:
  - platform: homeassistant
    entity_id:  climate.airco_lokaal_1_airco
    id: airco_1_state
    attribute: state

binary_sensor:
  - platform: template
    id: airco_1_switch
    lambda: |-
      if (id(airco_1_state).has_state()) {
        return id(airco_1_state).state == "off";
      }
      return false;
    on_state:
      then:
        lvgl.widget.update:
          id: lokaal1
          state:
            checked: !lambda return x;